/**
 * Generates the WordPress stylesheet from the site stylesheet.
 *
 * Every rule is scoped under `.mbb` so the plugin cannot collide with the
 * theme or with Elementor: generic class names like .section, .btn or .lead
 * only apply inside the plugin's own wrapper.
 *
 *   :root  → .mbb      (custom properties travel with the wrapper)
 *   body   → .mbb
 *   .btn   → .mbb .btn
 *
 * @font-face and keyframes are copied through untouched.
 *
 *   node tools/build-wp-css.js
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const SRC = path.join(ROOT, 'assets/css/styles.css');
const OUT = path.join(ROOT, 'wordpress/match-bilbao-bizkaia/assets/css/mbb.css');

const SCOPE = '.mbb';

/** Scope a single comma-separated selector list. */
function scopeSelector(sel) {
  return sel
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean)
    .map((s) => {
      if (s === ':root' || s === 'body' || s === 'html') return SCOPE;
      if (s === '*' || s.startsWith('*,') || s === '*::before' || s === '*::after') {
        return SCOPE + ' *';
      }
      // Pseudo-elements attached to the root (::selection) stay global-ish.
      if (s.startsWith('::')) return SCOPE + ' ' + s;
      if (s.startsWith('html ') || s.startsWith('body ')) {
        return SCOPE + ' ' + s.replace(/^(html|body)\s+/, '');
      }
      return SCOPE + ' ' + s;
    })
    .join(',\n');
}

const css = fs.readFileSync(SRC, 'utf8');

let out = '';
let i = 0;

while (i < css.length) {
  // Carry whitespace across untouched — otherwise the next token is no longer
  // at position i and an @-rule gets mistaken for a selector.
  const ws = /^\s+/.exec(css.slice(i));
  if (ws) { out += ws[0]; i += ws[0].length; continue; }

  // Comments are copied verbatim.
  if (css.startsWith('/*', i)) {
    const end = css.indexOf('*/', i + 2);
    const stop = end === -1 ? css.length : end + 2;
    out += css.slice(i, stop);
    i = stop;
    continue;
  }

  // At-rules
  if (css[i] === '@') {
    const braceAt = css.indexOf('{', i);
    const semiAt = css.indexOf(';', i);
    if (braceAt === -1 || (semiAt !== -1 && semiAt < braceAt)) {
      out += css.slice(i, semiAt + 1); // @import / @charset
      i = semiAt + 1;
      continue;
    }

    const prelude = css.slice(i, braceAt).trim();
    // Find the matching closing brace.
    let depth = 0;
    let j = braceAt;
    for (; j < css.length; j++) {
      if (css[j] === '{') depth++;
      else if (css[j] === '}') { depth--; if (!depth) break; }
    }
    const body = css.slice(braceAt + 1, j);

    if (/^@(font-face|keyframes|-webkit-keyframes|page)/.test(prelude)) {
      out += prelude + ' {' + body + '}\n';           // copied as is
    } else {
      out += prelude + ' {\n' + scopeBlockList(body) + '\n}\n'; // @media, @supports
    }
    i = j + 1;
    continue;
  }

  // Plain rule
  const braceAt = css.indexOf('{', i);
  if (braceAt === -1) { out += css.slice(i); break; }

  let depth = 0;
  let j = braceAt;
  for (; j < css.length; j++) {
    if (css[j] === '{') depth++;
    else if (css[j] === '}') { depth--; if (!depth) break; }
  }

  const sel = css.slice(i, braceAt).trim();
  const body = css.slice(braceAt + 1, j);
  if (sel) out += scopeSelector(sel) + ' {' + body + '}\n';
  i = j + 1;
}

/** Scope every rule inside an at-rule body. */
function scopeBlockList(block) {
  let res = '';
  let k = 0;
  while (k < block.length) {
    if (block.startsWith('/*', k)) {
      const end = block.indexOf('*/', k + 2);
      const stop = end === -1 ? block.length : end + 2;
      res += block.slice(k, stop);
      k = stop;
      continue;
    }
    const b = block.indexOf('{', k);
    if (b === -1) { res += block.slice(k); break; }
    let d = 0;
    let e = b;
    for (; e < block.length; e++) {
      if (block[e] === '{') d++;
      else if (block[e] === '}') { d--; if (!d) break; }
    }
    const sel = block.slice(k, b).trim();
    if (sel) res += '  ' + scopeSelector(sel) + ' {' + block.slice(b + 1, e) + '}\n';
    k = e + 1;
  }
  return res;
}

// Fonts live one folder up from the stylesheet in both layouts, so the
// ../fonts/ references keep working as they are.
// The modal locks the page, and the page is the theme's <body> — the only rule
// that has to live outside the wrapper.
const GLOBAL = `
/* --- outside the wrapper on purpose ------------------------------------- */
body.mbb-no-scroll { overflow: hidden; }
`;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(
  OUT,
  '/* Generated by tools/build-wp-css.js — edit assets/css/styles.css instead. */\n' +
    out +
    GLOBAL
);

console.log('Wrote %s (%d KB)', path.relative(ROOT, OUT), Math.round(out.length / 1024));
